apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eks-efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0f0386c44bc9d7157
  directoryPerms: "777"
