apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eks-efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0adf402a3f073a7b1
  directoryPerms: "777"
