apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lib-ingress
  namespace: k8s
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # Ensures requests are properly routed
spec:
  rules:
    - host: library.local # Domain name for accessing the service
      http:
        paths:
          - path: / # Path to route to backend
            pathType: Prefix
            backend:
              service:
                name: backend-service # Backend service name
                port:
                  number: 5000 # Port where the backend serivce is exposed

