apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: k8s
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: eks-efs-sc
  resources:
    requests:
      storage: 1Gi
