apiVersion: v1
kind: PersistentVolume
metadata:
  name: lib-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/k8s/mnt/lib-app-data/"
  persistentVolumeReclaimPolicy: Retain
